import 'dart:io';
import 'package:drift/drift.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../../../core/storage/database.dart';

class BookNotesExporter {
  final AppDatabase db;

  BookNotesExporter(this.db);

  Future<String> generateMarkdown(int bookId) async {
    final bookResults = await (db.select(db.books)
          ..where((t) => t.id.equals(bookId)))
        .get();
    if (bookResults.isEmpty) return '';
    final book = bookResults.first;

    final chapters = await db.getChaptersForBook(bookId);

    final bookmarkList = await (db.select(db.bookmarks)
          ..where((t) => t.bookId.equals(bookId))
          ..orderBy([(t) => OrderingTerm.asc(t.createdAt)]))
        .get();

    final highlightList = await (db.select(db.highlights)
          ..where((t) => t.bookId.equals(bookId))
          ..orderBy([(t) => OrderingTerm.asc(t.createdAt)]))
        .get();

    final glossaryList = await (db.select(db.glossaryTerms)
          ..where((t) => t.bookId.equals(bookId))
          ..orderBy([(t) => OrderingTerm.asc(t.sourceTerm)]))
        .get();

    final sb = StringBuffer();
    sb.writeln('# ${book.title}');
    if (book.author != null && book.author!.isNotEmpty) {
      sb.writeln('**Author:** ${book.author}');
    }
    sb.writeln('**Exported:** ${DateTime.now().toLocal().toString().substring(0, 16)}');
    sb.writeln('');
    sb.writeln('---');
    sb.writeln('');

    if (highlightList.isNotEmpty) {
      sb.writeln('## Highlights (${highlightList.length})');
      sb.writeln('');
      for (final h in highlightList) {
        final chapterName = chapters.where((c) => c.id == h.chapterId).map((c) => c.title).firstOrNull ?? 'Unknown';
        final colorEmoji = _colorToEmoji(h.color);
        sb.writeln('### $colorEmoji $chapterName');
        sb.writeln('');
        sb.writeln('> ${h.startAnchor}');
        if (h.endAnchor != h.startAnchor && h.endAnchor.isNotEmpty) {
          sb.writeln('> ${h.endAnchor}');
        }
        if (h.note != null && h.note!.isNotEmpty) {
          sb.writeln('');
          sb.writeln('**Note:** ${h.note}');
        }
        sb.writeln('');
        sb.writeln('*${_formatDate(h.createdAt)}*');
        sb.writeln('');
      }
    }

    final bookmarksWithContent = bookmarkList.where((b) =>
        (b.label != null && b.label!.isNotEmpty) ||
        (b.note != null && b.note!.isNotEmpty)).toList();

    if (bookmarksWithContent.isNotEmpty) {
      sb.writeln('## Bookmarks (${bookmarksWithContent.length})');
      sb.writeln('');
      for (final b in bookmarksWithContent) {
        final chapterName = chapters.where((c) => c.id == b.chapterId).map((c) => c.title).firstOrNull ?? 'Unknown';
        final label = b.label ?? 'Bookmark';
        sb.writeln('- **$label** - $chapterName');
        if (b.note != null && b.note!.isNotEmpty) {
          sb.writeln('  - ${b.note}');
        }
        sb.writeln('  - *${_formatDate(b.createdAt)}*');
      }
      sb.writeln('');
    }

    if (glossaryList.isNotEmpty) {
      sb.writeln('## Terminology (${glossaryList.length})');
      sb.writeln('');
      for (final g in glossaryList) {
        sb.writeln('- **${g.sourceTerm}** (${g.sourceLanguage} -> ${g.targetLanguage}): ${g.preferredTranslation}');
      }
      sb.writeln('');
    }

    final stats = await db.getReadingStats(bookId);
    final totalSeconds = stats['totalSeconds'] ?? 0;
    final hours = totalSeconds ~/ 3600;
    final minutes = (totalSeconds % 3600) ~/ 60;

    sb.writeln('## Reading Stats');
    sb.writeln('');
    sb.writeln('- **Total Reading Time:** ${hours}h ${minutes}m');
    sb.writeln('- **Chapters Read:** ${stats['totalChapters'] ?? 0}');
    sb.writeln('- **Words Translated:** ${stats['totalWordsTranslated'] ?? 0}');
    sb.writeln('- **Reading Sessions:** ${stats['totalSessions'] ?? 0}');
    sb.writeln('');
    sb.writeln('---');
    sb.writeln('*Generated by Alinea Reader*');

    return sb.toString();
  }

  Future<void> exportAndShare(int bookId, String title) async {
    final markdown = await generateMarkdown(bookId);
    if (markdown.isEmpty) return;

    final dir = await getApplicationDocumentsDirectory();
    final safeTitle = title.replaceAll(RegExp(r'[^\w\s-]'), '').replaceAll(' ', '_');
    final file = File('${dir.path}/${safeTitle}_notes.md');
    await file.writeAsString(markdown, flush: true);

    await Share.shareXFiles(
      [XFile(file.path)],
      subject: 'Book Notes: $title',
      text: 'Reading notes for $title exported from Alinea',
    );
  }

  String _colorToEmoji(String color) {
    switch (color) {
      case 'yellow': return '\u{1F7E1}';
      case 'green': return '\u{1F7E2}';
      case 'blue': return '\u{1F535}';
      case 'pink': return '\u{1F534}';
      default: return '\u{2B1B}';
    }
  }

  String _formatDate(DateTime dt) {
    return '${dt.day.toString().padLeft(2, '0')}/${dt.month.toString().padLeft(2, '0')}/${dt.year}';
  }
}
